#!/bin/bash

mostrar_menu() {
    echo "seleciona una operacion:"
    echo "1- Suma"
    echo "2- Resta"
    echo "3- Multiplicacion" 
    echo "4- Division"
    echo "5- Salir" 

}

echo " ingresa el primer numero:"
read numero1
echo "ingresa el segundo numero:"
read numero2

while true; do
    mostrar_menu
    read -p "opcion: " opcion

    case $opcion in

    1)resultado=$((numero1 + numero2))
    echo "Resultado de la suma: $numero1 + $numero2 = $Resultado" ;;
    2)resultado=$((numero1 - numero2))
    echo "Resultado de la resta: $numero1 - $numero2 = $Resultado" ;;
    3)resultado=$((numero * numero2))
    echo "Resultado de la multiplicacion: $numero1 * $numero2 = $Resultado" ;;

    4)if["$numero2" -ne 0]; 
        then
        resultado=$(echo "scale=2; $numero1/ $numero2" | bc) 
            echo "resultado de la division: $numero1 / $numero2 = $resultado"

        else
            echo "error: no se puede dividir entre o"
        fi ;;
    5)echo "saliendo del programa"
            break ;;
    *)echo "opcion invalida, por favor elige una opcion del 1 al 5" ;;
    

        esac
        echo " "
        
    done
