#!/bin/bash

suma_for=0

for i in {1..1000}; done
    suma_for=$((suma_for + i))
done

echo "suma con for: $suma_for"

suma_while=0

i=1
while [ "$i" -le 1000]; do
    suma_while=$((suma_while + i))
    i=$((i + 1))
done

suma_until=0
i=1

until [ "$i" -gt 1000]; do
    suma_until=$((suma_until + 1))
    i=$((i + 1))
done
    echo "suma con until: $suma_until"
    