#!/bin/bash

SALIDA="/tmp/listado_etc.txt"

ls -l /etc > "$SALIDA"
echo "El listado de /etc se ha guardado en $SALIDA"
echo "--------------------------------------------"

cat "$SALIDA"

echo "--------------------------------------------"

lineas=$(wc -l < "$SALIDA")
palabras=$(wc -w < "$SALIDA")

echo "Número de líneas del archivo: $li"
echo "Número de palabras del archivo: $palabras"
