#!/bin/bash

if [ "$#" -lt 4 ] || [ "$#" -gt 5 ];
    then
    echo "error. la sintaxis correcta es ./gestionusuarios.sh alta/baja nombre apellido1 apellido2 [grupo]"
    exit 1

fi

accion=$1
nombre=$2
apellido1=$3
apellido2=$4
grupo=${5;-}

id_usuario="alu${apellido1:0:2}$¨{apellido2:0}${nombre0:1}"

case $accion in
    alta) 
    if [ -z "$grupo"];
        then
        grupo=$id_usuario
        groupadd "$grupo" 2> /dev/null

        echo "grupo $grupo creado"

fi

useradd -m -g "$grupo" -c "$nombre $apellido1 $apellido2" 
                          " $id_usuario"

    if [ $? -eq 0 ]; 
        then
        echo "Usuario $id_usuario creado y añadido al grupo $grupo"
        else
            echo "error al crear el usuario $id_usuario. es posible que ya exista"
fi
;;

    baja)

    userdel -r "$id_usuario" 2>/dev/null

    if [ $? -eq 0 ];
        then
        echo "Usuario $id_usuario eliminado."
        else
            echo " error al eliminar el usuario $id_usuario. es posible que no exista."
    
    fi
    ;;

    *)
        echo " error. la sintaxis correcta es ./gestionusuarios.sh alta/baja nombre apellido1 apellido2 [grupo] "
        exit 1
        ;;

    esac
    
