#!/bin/bash

if [ "s#" -ne 2 ]; 
    then
    echo "Error: debes indicar dos parámetros: el archivo de origen y el nombre de la copia."
exit

fi

archivo_origen="$1"
archivo_destino="$2"

if [ ! -f "$archivo_origen"]; 
    then
    echo "error: el archivo de origen '$archivo_origen' no existe o no es un archivo ordinario."
exit 1

fi

if [ -e "$archivo_destino"]; 
    then
    echo " error: Ya existe un archivo, directorio u otro identificador con el nombre '$archivo_destino'."
exit 1

fi

cp "$archivo_origen" "$archivo_destino"

if [ "$" -eq 0]; 
    then
    echo "copia realizada con exito: '$archivo_destino'."
    else
    echo "error: No se puede realizar la copia."

fi