#!/bin/bash

if [ -z "$1"]; then
 echo " por favor, proporciona nombre de directorio"
 exit

 fi

 if [ ! -d "$directorio"]; then
    echo "el directorio '$directorio' no existe "
 exit

 fi

 fecha=$(date +%F)

nombre_del_archivo="${fecha}_$(basename "$directorio").tar.gz"

tar -cfz "nombre_archivo" "$directorio"

echo "archivo comprimido creado: $nombre_archivo"